### ISSUE TITLE
Small file test aborts on windows after few iterations

### ISSUE THREAD

**Issue by ksandha** [bengland2/smallfile#3]
launch_host_smf on secondary node and start create, mkdir operation on the main node. Test aborts on the main node  

Logs placed at https://drive.google.com/drive/folders/0B8kUR8TCDdh3Mk1rclVvNHBfaGc?usp=sharing

**Comment by bengland2** [comment]
I'm not seeing any exceptions thrown in invoke*log, just threads are seeing that test aborted (should be an abort file in z:\\smf\\network_shared somewhere.

in windows-worker launch-host.txt:
Exception: starting signal not seen within 175 seconds

so this looks like client aborted in middle of starting a test.
in windows-worker invoke logs you will see at end messages like this:
02 2017-07-06 03:42:54,632 - ERROR - thread 02 saw abort flag
which means this thread wasn't the one that encountered the error

it appears that **mkdir** and **rmdir** operations completed, it was the subsequent **create** operation that aborted.

Could you do me a favor and completely clean out z:\\smf  and try this again?  I want to make sure it wasn't just because some file was left over in the tree from a previous test?  If the problem happens again, then do the **cleanup** op and retry create.  Because it looked like create worked the first time, but didn't work the 2nd time.  This could happen if a lower number of files was chosen for cleanup command, for example - create assumes that no files are present in the directory tree when it starts, and should throw an exception if files are already there.

**Comment by ksandha** [comment]
Hi bene,

Seems like there were old logs in the invoke*.log. When i faced the issue I was using a freshly formatted gluster volume. Though i will reproduce it again and update the issue.

Thanks & regards

Karan Sandha

**Comment by bengland2** [comment]
closed since I haven't heard anything new about it.
