### ISSUE TITLE
Meaning of this Error Message "ERROR: not enough total files processed, change test parameters"

### ISSUE THREAD

**Issue by ramendra-singh** [bengland2/smallfile#4]
What is the meaning of this error ?

```ERROR: not enough total files processed, change test parameters```

**Comment by bengland2** [comment]
This message is intended to warn users that 1 thread finished before 70% of the files were processed (see the rest of the summary output at the bottom).    smallfile aims to measure only while all threads are executing.  Otherwise you can have a situation where you aren't really running all threads concurrently, and this makes aggregation of per-thread results invalid.  However, it's impossible for smallfile to start all threads exactly at the same time.  Try running a longer test or use the --pause parameter to insert some delay into each thread.  If this doesn't work, post a pastebin of the output here and we'll take a look.

**Comment by ramendra-singh** [comment]
Thanks a lot for reply.
