### ISSUE TITLE
never reaching the 100% file processed

### ISSUE THREAD

**Issue by labazza** [bengland2/smallfile#6]
I am running a series of tests, the --create operation which is the first performed never reaches the 100% of file processed and actually almost always ends up with an 87,5%. This happens no matter the number of files/threads/fsync/pause options i use. This of course cause subsequent operations  to reach 62%, 80%, 25% etc.
It seems to me there is a timeout somewhere that stops the operation execution no matter how many files i want to process. 
I am running the test on 9 clients with 24 cores each, for instance:
                            files/thread : 200
                                 threads : 2
           record size (KB, 0 = maximum) : 0
                          file size (KB) : 64
                  file size distribution : fixed
                           files per dir : 100
                            dirs per dir : 10
              threads share directories? : N
                         filename prefix : fsync_
                         filename suffix : 
             hash file number into dir.? : N
                     fsync after modify? : Y
          pause between files (microsec) : 300
                    finish all requests? : Y
                              stonewall? : Y
                 measure response times? : N
                            verify read? : Y
                                verbose? : False
                          log to stderr? : False
                           ext.attr.size : 0
                          ext.attr.count : 0
               permute host directories? : N

example output:
total threads = 16
total files = 2800
total IOPS = 2800
total data =     0.171 GiB
 87.50% of requested files processed, minimum is  90.00
elapsed time =     3.961
files/sec = 706.826175
IOPS = 706.826175
MiB/sec = 44.176636
not enough total files processed, change test parameters

**Comment by bengland2** [comment]
Is there some subset of the clients that does not have this problem?  I have seen problems like this before - is it possible that there is some degree of unfairness in your distributed filesystem that is preventing some of the clients from gaining access?  

I notice in the above example that you have --fsync Y --pause 300, but only 200 files per thread, not many for a distributed multi-client test.  It takes a second or two for the threads to all start running in the current implementation and with a small number of files per thread, some of the threads may finish before others get started.    try a larger number of files/thread.    

If that doesn't work, try increasing per-file think time to something like 1/10th of your per-file latency for that operation type - some file operation types have very low latency so that this option will throttle throughput.

You can get response time data using --response-times Y and you can then see whether there are differences between clients in response time.

> This of course cause subsequent operations to reach 62%, 80%, 25% etc.

I don't think so.  Create operations should create the same number of files per thread, only *measurement* of throughput stops when the first thread completes, and the other threads continue to run until they have processed all files.  

HTH, Let us know how this turns out.

**Comment by labazza** [comment]
i have changed the gluster cluster to a different deployment.
i have increased the files to 20000 with 2 threads and i reach higher percentages like 98%; however sometimes in this configuration i receive the exception "hosts did not reach starting gate within 11 seconds" and 11 seconds is always 11 seconds (maybe this can be increased?). I couldn't find anything in /var/tmp/invoke_logs-*.log
This happens during the create operation before "starting all threads by creating starting gate file /mnt/glusterfs/vol_md00/network_shared/starting_gate.tmp".
So i have decreased the number of files to 10000 and this made the workload create the files and reach a 97%. Anyways my IOPS during create still aprox 1150 with fsync.
I am running it in 8 clients a mix of centos 6.8 and 7.4 varying 24 to 32 cores.

**Comment by bengland2** [comment]
11 seconds isn't hardcoded, it is calculated as a function of the number of files per thread and number of threads and number of hosts, [here](https://github.com/bengland2/smallfile/blob/master/smf_test_params.py#L58) .  This delay is intended to give the distributed storage time to create the necessary directories before the test, so that the test is not measuring directory creation time (unless you request this with --operation mkdir).  It is possible to change this code to increase the time that it will wait for threads to become ready (see hyperlink above), Doing some arithmetic, you have 9 clients with 2 threads/client and 100 files/directory, so 20000 files/thread = 200 directories per thread, so total directory count is 200 x 2 x 9 = 3600 directories.  so we would have to create 360 directories per second to meet this time constraint.   Perhaps this timeout needs to be increased.  Try adjusting the calculation above, I can do it for you if you don't know how.    If that resolves your problem then we'll fix it in github as this may affect others.

**Comment by bengland2** [comment]
thank you for trying this, obviously there is more work to do here because
of the related timeouts.

One other workaround that I did not think of at the time - increase files
per directory, since this means fewer directories have to be created up
front.

You can see the directory structure that is being created by looking in
$topdir/file_srcdir/host/thread/

**Comment by labazza** [comment]
yes that works. So a combination of:
- removing //3 at https://github.com/bengland2/smallfile/blob/469b2f16084dc336f238410a49b8a9f32933c334/smf_test_params.py#L58
- 1000 files per dir
i am able to run the test with 50000 files * 8 threads * 7 clients on a gluster fuse mount
I believe this should be enough for various use cases. I will continue testing with NFS... thanks for the moment for the help!

**Comment by labazza** [comment]
hi, i have noticed that with the --create operation, folder file_dstdir gets created with a folder structure same as file_srcdir but without files. i don't understand it's use and i think is creating more directories than needed?

**Comment by bengland2** [comment]
That's true for many operation types.  It could look at the --operation type and see whether it needed that or not.   However, in the case of --operation rename or --delete-renamed, this tree does get used, that's probably why I just created it every time.  I have a separate tree because renaming from one directory to another can be a real performance drag for distributed filesystems, at least in some cases.   

However, in the worst case it creates twice as many directories as are needed, but that should not place much load on the filesystem normallly.   Typically the directories are only created during the first test and are just left there for subsequent operation types to use.  So I would think that we shouldn't have to change this behavior, we just need to increase the timeout.

**Comment by bengland2** [comment]
I'm closing this because there is another issue #5 open currently on the timeout issue, and I think we resolved the question about what the %files processed in your initial post.  I'm working on fixing the timeout issue there.
